In [4]:
import numpy as np

# 1D array###

In [5]:
a=np.array([15,25,14,78,96])

In [6]:
a

array([15, 25, 14, 78, 96])

## CHANGING THE DATATYPE ###

In [9]:
a.dtype

dtype('float64')

In [10]:
a=np.array([15,25,14,78,96],dtype="float")

In [11]:
a

array([15., 25., 14., 78., 96.])

In [12]:
a.dtype

dtype('float64')

### CREATING THE SEQUENCE OF NUMBERS ##

In [15]:
b = np.arange(start=20,stop=30,step=3)

In [16]:
b

array([20, 23, 26, 29])

In [17]:
c= np.arange(start=20,stop=30,step=2)

In [18]:
c

array([20, 22, 24, 26, 28])

## INDEXING IN ARRAYS ###

### X[START:END:STEP]

### X[START:END]

### X[START:]

### X[:END]

In [19]:
x=np.arange(10)

#x[2:5]
#x[::2]
#x[1::2]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x=np.arange(10)
x[9]

9

In [22]:
x=np.arange(10)

In [23]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x=np.arange(10)
x[2:5]

array([2, 3, 4])

In [25]:
x=np.arange(10)
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
x=np.arange(10)
x[1::2]

array([1, 3, 5, 7, 9])

In [27]:
x[:7:3]=127

In [28]:
x

array([127,   1,   2, 127,   4,   5, 127,   7,   8,   9])

In [29]:
x=np.arange(20)
x[::-3]

array([19, 16, 13, 10,  7,  4,  1])

## RESHAPING THE ARRAYS ##

In [30]:
f=np.arange(101,113)

f

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

In [31]:
f.reshape(4,3)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109],
       [110, 111, 112]])

In [32]:
f.resize(4,3)

In [33]:
f

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109],
       [110, 111, 112]])

In [34]:
f.reshape(3,-1)

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

## MISSING DATA ##

In [35]:
val=np.array([15,10,np.nan,3,2,5,6,4])

In [36]:
val

array([15., 10., nan,  3.,  2.,  5.,  6.,  4.])

In [37]:
val.sum()

nan

In [38]:
np.nansum(val)

45.0

In [39]:
np.isnan(val)

array([False, False,  True, False, False, False, False, False])

## 2D arrays ##

In [41]:
g=np.array([(10,20,30),(40,50,60)])

In [42]:
g

array([[10, 20, 30],
       [40, 50, 60]])

In [43]:
g=np.array([[10,20,30],[40,50,60]])
g

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
g.ndim

2

In [45]:
g.size

6

In [46]:
g.shape

(2, 3)

## CREATING SOME USUAL MATRICES ##

### Zero

In [47]:
x=np.zeros((2,4))

In [48]:
x.dtype

dtype('float64')

In [49]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.zeros([2,4],dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [51]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### One

In [52]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Diagonal

In [53]:
np.diag([14,15,16,17])

array([[14,  0,  0,  0],
       [ 0, 15,  0,  0],
       [ 0,  0, 16,  0],
       [ 0,  0,  0, 17]])

### Eye

In [54]:
y=np.eye(5,dtype="int")
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## RESHAPING 2D ARRAYS ##

In [55]:
g=np.arange(10,70,10)

In [56]:
g.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [57]:
g.reshape(3,-1)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [58]:
g.shape

(6,)

In [59]:
g.resize((3,2))

In [60]:
g

array([[10, 20],
       [30, 40],
       [50, 60]])

## TIME FOR MATRIX ALGEBRA ##

In [61]:
A=np.array([[2,0,1],[4,3,8],[7,6,9]])
b=np.array([1,101,14])
B=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [62]:
A

array([[2, 0, 1],
       [4, 3, 8],
       [7, 6, 9]])

In [63]:
b

array([  1, 101,  14])

In [64]:
B

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [65]:
A.T

array([[2, 4, 7],
       [0, 3, 6],
       [1, 8, 9]])

In [66]:
A.transpose()

array([[2, 4, 7],
       [0, 3, 6],
       [1, 8, 9]])

In [67]:
np.trace(A)

14

In [69]:
np.linalg.inv(A)

array([[ 0.53846154, -0.15384615,  0.07692308],
       [-0.51282051, -0.28205128,  0.30769231],
       [-0.07692308,  0.30769231, -0.15384615]])

### MATRIX ADDITION AND SUBSTRACTION ##

In [70]:
A+B

array([[12, 20, 31],
       [44, 53, 68],
       [77, 86, 99]])

In [71]:
A-B

array([[ -8, -20, -29],
       [-36, -47, -52],
       [-63, -74, -81]])

In [72]:
B

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
A

array([[2, 0, 1],
       [4, 3, 8],
       [7, 6, 9]])

In [74]:
B-A

array([[ 8, 20, 29],
       [36, 47, 52],
       [63, 74, 81]])

In [75]:
A.dot(B)

array([[  90,  120,  150],
       [ 720,  870, 1020],
       [ 940, 1160, 1380]])

In [76]:
A

array([[2, 0, 1],
       [4, 3, 8],
       [7, 6, 9]])

In [77]:
B

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [78]:
np.linalg.eig(A)

(array([14.0874236 ,  1.62072127, -1.70814487]),
 array([[-0.06599631, -0.78226966, -0.14996331],
        [-0.59939873,  0.54774477, -0.81748379],
        [-0.7977253 ,  0.29669824,  0.55608566]]))

## SOME MATHEMATICS FUNCTIONS ##

In [79]:
B=np.array([[0,-20,36],[40,50,1]])
np.sin(B)

array([[ 0.        , -0.91294525, -0.99177885],
       [ 0.74511316, -0.26237485,  0.84147098]])

In [80]:
c=B**2

In [81]:
c

array([[   0,  400, 1296],
       [1600, 2500,    1]], dtype=int32)

In [82]:
B>25

array([[False, False,  True],
       [ True,  True, False]])

In [83]:
np.absolute(B)

array([[ 0, 20, 36],
       [40, 50,  1]])

In [84]:
np.sqrt(B)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[0.        ,        nan, 6.        ],
       [6.32455532, 7.07106781, 1.        ]])

In [85]:
np.exp(B)

array([[1.00000000e+00, 2.06115362e-09, 4.31123155e+15],
       [2.35385267e+17, 5.18470553e+21, 2.71828183e+00]])

In [86]:
A=np.arange(1,10).reshape(3,3)

In [87]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
A.sum()

45

In [89]:
A.min()

1

In [90]:
A.max()

9

In [91]:
A.std()

2.581988897471611

In [92]:
A.mean()

5.0

In [93]:
A.var()

6.666666666666667

In [94]:
A.argmin()

0

In [95]:
A.argmax()

8

In [96]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
A.sum(axis=0)

array([12, 15, 18])

In [98]:
A.sum(axis=1)

array([ 6, 15, 24])

In [99]:
A.mean(axis=0)

array([4., 5., 6.])

In [100]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [101]:
A.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [122]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
A.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [105]:
A.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

## CREATING 3D ARRAY ##

In [106]:
X=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [107]:
X

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [108]:
X.shape

(1, 4, 3)

In [109]:
X.ndim

3

In [110]:
X.size

12

In [111]:
X.sum(axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
X.sum(axis=1)

array([[22, 26, 30]])

In [113]:
X.sum(axis=2)

array([[ 6, 15, 24, 33]])

In [114]:
X.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
X = np.array( [[[ 1, 2,3], 
[ 4, 5, 6]],
[[7,8,9],
[10,11,12]]])

In [116]:
X

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [117]:
X[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [118]:
X[0]

array([[1, 2, 3],
       [4, 5, 6]])

## FIND OUT POSITION OF ELEMENTS THAT SATISFY A GIVEN CONDITION ##

In [123]:
a=np.array([8,3,7,0,4,2,5,2])
np.where(a>4)

(array([0, 2, 6], dtype=int64),)

## INDXING WITH ARRAYS OF INDICES ##

In [126]:
x=np.arange(11,35,2)
x

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [127]:
i=np.array([0,1,5,3,7,9])
x[i]

array([11, 13, 21, 17, 25, 29])

In [128]:
j=np.array([[0,1],[6,2]])
x[j]

array([[11, 13],
       [23, 15]])

# similar we can create both i and j as 2D arrays of indcies for x#

In [142]:
x=np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
i=np.array([[0,1],[2,0]])#indices for first dim 
j=np.array([[1,1], [2,0]])#indices for second dim

In [131]:
i

array([[0, 1],
       [2, 0]])

In [132]:
j

array([[1, 1],
       [2, 0]])

In [136]:
x[i]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [143]:
x[j]

array([[[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [144]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
x[i,j]

array([[ 1,  6],
       [12,  0]])

In [140]:
x[i,2]

array([[ 2,  7],
       [12,  2]])

In [141]:
x[j]

array([[[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [138]:
x[:,j]

array([[[ 1,  1],
        [ 2,  0]],

       [[ 6,  6],
        [ 7,  5]],

       [[11, 11],
        [12, 10]]])

In [145]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
x[[4,5,8,1,2]]=0
x

array([0, 0, 0, 3, 0, 0, 6, 7, 0, 9])

In [147]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
x[[4,4,2,3]]=[100,200,300,400]
x

array([  0,   1, 300, 400, 200,   5,   6,   7,   8,   9])

In [149]:
x=np.arange(10)

In [151]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
x[[1,1,1,7,7]]+=1

In [153]:
x

array([0, 2, 2, 3, 4, 5, 6, 8, 8, 9])

## IDEXING WITH BOOLEAN ARRAYS ##

In [155]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [161]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [162]:
a[b]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [163]:
x=np.arange(15).reshape(3,5)
y=np.array([True,True,False]) #First dim selection
z=np.array([True,True,False,True,False])#second dim selection

In [164]:
x[y,:]#Selecting rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [165]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [166]:
x[y,:]#Selecting rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [167]:
x[y]#Same thing

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [168]:
x[:,z]# selecting columns

array([[ 0,  1,  3],
       [ 5,  6,  8],
       [10, 11, 13]])

## STATISTICS ON PANDAS DATAFRAME ##

In [169]:
import pandas as pd

In [170]:
np.random.seed(234)
mydata=pd.DataFrame({"x1":np.random.randint(low=1,high=100,size=10),"x2":range(10)})

In [171]:
mydata

x1  x2
0  73   0
1  32   1
2  69   2
3  58   3
4  96   4
5  34   5
6   4   6
7  55   7
8  64   8
9  68   9

### Calculate mean of each column of Dataframe ##

In [172]:
np.mean(mydata)

x1    55.3
x2     4.5
dtype: float64

In [173]:
np.median(mydata,axis=0)

array([61. ,  4.5])

## Stacking various arrays ##

In [174]:
A=np.array([[10,20,30],[40,50,60]])
B=np.array([[100,200,300],[400,500,600]])

In [175]:
np.vstack((A,B)) # Stacking vertically

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300],
       [400, 500, 600]])

In [176]:
np.hstack((A,B))#Stacking Horizontally

array([[ 10,  20,  30, 100, 200, 300],
       [ 40,  50,  60, 400, 500, 600]])

In [177]:
from numpy import newaxis
a=np.array([4.,1.])
b=np.array([2.,8.])
a[:,newaxis]

array([[4.],
       [1.]])

In [178]:
b[:,newaxis]

array([[2.],
       [8.]])

In [179]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 2.],
       [1., 8.]])

## SPLITTING THE ARRAYS ##

In [180]:
import numpy as np

In [181]:
z=np.arange(1,16)

In [182]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [183]:
np.hsplit(z,5)

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15])]

In [184]:
np.hsplit(z,(3,5))

[array([1, 2, 3]),
 array([4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [9]:
np.hsplit(z,(3,5,10))

[array([1, 2, 3]),
 array([4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15])]

In [10]:
A=np.arange(1,31).reshape(3,10)

In [11]:
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [12]:
np.hsplit(A,5)

[array([[ 1,  2],
        [11, 12],
        [21, 22]]), array([[ 3,  4],
        [13, 14],
        [23, 24]]), array([[ 5,  6],
        [15, 16],
        [25, 26]]), array([[ 7,  8],
        [17, 18],
        [27, 28]]), array([[ 9, 10],
        [19, 20],
        [29, 30]])]

In [13]:
np.hsplit(A,(3,5))

[array([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]]), array([[ 4,  5],
        [14, 15],
        [24, 25]]), array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20],
        [26, 27, 28, 29, 30]])]

## COPYING ##

In [14]:
x=np.arange(1,16)

In [15]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
y=x
y is x

True

In [17]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
y.shape=3,5

In [19]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
x.shape

(3, 5)

## CREATING A VIEW OF THE DATA ##

In [21]:
z=x.view()
z is x

False

In [22]:
z.shape=5,3

In [23]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [24]:
x.shape

(3, 5)

In [25]:
x.view()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
z[0,0]=1234

In [27]:
x

array([[1234,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15]])

## CREATING A COPY OF DATA ##

In [28]:
z=x.copy()

In [29]:
z is x

False

In [30]:
z[0,0]=9999

In [31]:
x

array([[1234,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15]])

## EXERCISE NUMPY ##

In [32]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [33]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [36]:
x=np.array([5,6,7,8,3,4])
y=np.array([5,3,4,8,2,4])

In [37]:
np.where(x==y)

(array([0, 3, 5], dtype=int64),)

In [38]:
k=np.array([5,3,4,5,2,4])

In [41]:
L=k.max(),k.min()

In [42]:
L

(5, 2)

In [43]:
L_= (k-kmin)/(k-kmax)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


In [44]:
L_

array([ inf, -0.5, -2. ,  inf, -0. , -2. ])

In [45]:
p=np.array([15,10,3,2,5,6,4])

In [47]:
np.percentile(p,q=[5,50])

array([ 2.3,  5. ])

In [48]:
np.mean(p)

6.4285714285714288

In [49]:
np.median(p)

5.0

In [51]:
np.max(p)

15

In [52]:
np.min(p)

2

In [56]:
np.percentile(p,q=[93])

array([ 12.9])

In [57]:
p=np.array([5,10,np.nan,3,2,5,6,np.nan])

In [59]:
print("Number of missing values=",np.isnan(p).sum())

Number of missing values= 2


In [60]:
np.isnan(p)

array([False, False,  True, False, False, False, False,  True], dtype=bool)

In [62]:
np.isnan(p).sum()

2